version: "3.9"
services:
    product_db:
        image: postgres:latest
        restart: always
        container_name: product_db
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: vittenpass 
            POSTGRES_DB: product_database
          
    user_db:
        image: postgres:latest
        restart: always
        container_name: user_db
        ports:
            - 5435:5432
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: vittenpass 
            POSTGRES_DB: user_database
            
          
    backend:
        container_name: itembackend
        build: ./backendshop
        ports:
            - "5000:5050"
        depends_on:
            - product_db
            - user_db
        
   
    web:
        container_name: frontend
        build: ./front/web-app
        ports:
            - "80:3000"
        depends_on:
            - backend
        
volumes:
    database_postgres:





    
        
        
        
                      